import Link from "next/link";

export function OverlaySection() {
  const bullets = [
    "Board and list views",
    "Filters by state, priority, labels, repo",
    "PR linking by convention (branch and title)",
    "Read-only in v1, edit via git and CLI",
  ];

  return (
    <section className="border-t border-border">
      <div className="mx-auto max-w-6xl px-6 py-20">
        <h2 className="text-2xl font-semibold tracking-tight sm:text-3xl">
          A clean view over what&apos;s already in Git.
        </h2>
        <p className="mt-4 max-w-2xl text-muted">
          The dashboard reads{" "}
          <code className="rounded bg-surface-2 px-1.5 py-0.5 font-mono text-xs">
            .tickets/index.json
          </code>{" "}
          generated by the CLI, then loads individual ticket files on demand. No
          separate source of truth.
        </p>
        <ul className="mt-6 space-y-2">
          {bullets.map((b) => (
            <li key={b} className="flex items-start gap-2 text-sm text-muted">
              <span className="mt-0.5 text-success">&check;</span>
              {b}
            </li>
          ))}
        </ul>
        <div className="mt-6">
          <Link
            href="/dashboard"
            className="text-sm font-medium text-brand underline underline-offset-4 hover:text-brand/80"
          >
            Dashboard
          </Link>
        </div>
      </div>
    </section>
  );
}
