export default function DashboardOverlaySection() {
  return (
    <section className="mx-auto w-full max-w-6xl px-6 py-16">
      <div className="grid gap-10 md:grid-cols-2 md:items-start">
        <div>
          <h2 className="text-3xl font-semibold tracking-tight text-slate-950">A fast view over what's already in Git.</h2>
          <p className="mt-4 leading-relaxed text-slate-600">
            The dashboard reads <code className="rounded bg-slate-100 px-1">.tickets/index.json</code> generated by the
            CLI, then loads individual tickets on demand. No replatforming your workflow.
          </p>
          <ul className="mt-6 space-y-2 text-slate-700">
            <li>Kanban and list views</li>
            <li>Filter by state, priority, label, repo</li>
            <li>Auto-link PRs by branch and title convention</li>
          </ul>
          <p className="mt-4 text-sm text-slate-500">Dashboard is read-only in v1. Edit via CLI and git.</p>
        </div>
        <div className="rounded-3xl border border-slate-200 bg-slate-50 p-5">
          <p className="text-xs font-medium text-slate-600">Board snapshot from `index.json`</p>
          <div className="mt-4 grid grid-cols-2 gap-3 text-xs md:grid-cols-3">
            {[
              ["backlog", "2"],
              ["ready", "4"],
              ["in_progress", "3"],
              ["blocked", "1"],
              ["done", "6"],
            ].map(([state, count]) => (
              <div key={state} className="rounded-2xl border border-slate-200 bg-white p-3">
                <p className="font-medium text-slate-700">{state}</p>
                <p className="mt-1 text-slate-500">{count} tickets</p>
              </div>
            ))}
          </div>
        </div>
      </div>
    </section>
  );
}
