import { slugifyTitle } from "./slugify.js";
import type { TicketChangePatch } from "./types.js";

export function buildTicketChangeBranchName(shortId: string, now = new Date()): string {
  const sid = shortId.toLowerCase();
  const stamp = toStamp(now);
  return `ticket-change/${sid}/${stamp}`;
}

export function buildPrTitle(displayId: string, summary: string): string {
  return `[${displayId}] ticket change: ${summary}`;
}

export function buildPrBody(args: {
  displayId: string;
  owner: string;
  repo: string;
  shortId: string;
  patch: TicketChangePatch;
  appBaseUrl?: string;
}): string {
  const base = args.appBaseUrl ?? "https://ticket.app";
  const link = `${base}/space/${args.owner}/${args.repo}/t/${args.displayId}`;
  const lines: string[] = [];
  lines.push("Generated by ticket.app dashboard.");
  lines.push("");
  lines.push(`Ticket: ${link}`);
  lines.push("");
  lines.push("Changes:");
  for (const [k, v] of Object.entries(args.patch)) {
    if (v !== undefined) {
      lines.push(`- ${k}: ${formatValue(v)}`);
    }
  }
  lines.push("");
  lines.push("Git is authoritative. This PR updates ticket frontmatter and index.json.");
  return lines.join("\n");
}

export function buildCanonicalCodeBranchName(shortId: string, title: string): string {
  return `tk-${shortId.toLowerCase()}-${slugifyTitle(title)}`;
}

function toStamp(d: Date): string {
  const pad = (n: number) => String(n).padStart(2, "0");
  return (
    d.getUTCFullYear() +
    pad(d.getUTCMonth() + 1) +
    pad(d.getUTCDate()) +
    "-" +
    pad(d.getUTCHours()) +
    pad(d.getUTCMinutes()) +
    pad(d.getUTCSeconds())
  );
}

function formatValue(v: unknown): string {
  if (v === null) return "null";
  if (Array.isArray(v)) return `[${v.join(", ")}]`;
  if (typeof v === "object") return JSON.stringify(v);
  return String(v);
}
